-- ===================================================
-- SEED DATABASE WITH DEMO DATA
-- ===================================================

\echo '--- Truncating all tables ---'
TRUNCATE TABLE results, exams, exercises, lessons, game_items, users RESTART IDENTITY CASCADE;

\echo '--- Inserting Users ---'
INSERT INTO users (username, password_hash, full_name, role, level) VALUES
('admin', 'admin123', 'System Admin', 'admin', 'advanced'),
('teacher', 'teacher123', 'English Teacher', 'teacher', 'advanced'),
('student_beg', '123456', 'Beginner Student', 'student', 'beginner'),
('student_int', '123456', 'Intermediate Student', 'student', 'intermediate'),
('student_adv', '123456', 'Advanced Student', 'student', 'advanced');

\echo '--- Inserting Lessons ---'
INSERT INTO lessons (title, topic, level, video_url, audio_url, text_content, vocabulary, grammar, created_by) VALUES
(
    'Daily Routine', 
    'Daily Life', 
    'beginner', 
    'https://www.youtube.com/watch?v=zNdpi9ZUSQE', 
    'https://example.com/audio/daily_routine.mp3', 
    'I wake up at 7 AM every morning. First, I brush my teeth and wash my face. Then, I eat breakfast with my family. Usually, I have toast and coffee. After breakfast, I get dressed and go to work. I take the bus to the office. I start work at 9 AM. At 12 PM, I have lunch with my colleagues. I finish work at 5 PM and go home. In the evening, I cook dinner and watch TV. I go to bed at 10 PM.',
    '[{"word": "wake up", "meaning": "stop sleeping"}, {"word": "breakfast", "meaning": "first meal of the day"}, {"word": "colleague", "meaning": "person you work with"}]'::jsonb,
    '[{"rule": "Present Simple", "example": "I wake up at 7 AM."}, {"rule": "Time Prepositions", "example": "at 7 AM, in the evening"}]'::jsonb,
    2
),
(
    'Job Interview Tips', 
    'Career', 
    'intermediate', 
    'https://www.youtube.com/watch?v=1mHjMNZE88w', 
    'https://example.com/audio/job_interview.mp3',
    'Preparing for a job interview is crucial for success. First, research the company to understand their values and products. Practice common interview questions, such as "Tell me about yourself" and "What are your strengths and weaknesses?". Dress professionally to make a good first impression. During the interview, maintain eye contact and speak clearly. Be honest about your skills and experiences. Finally, ask thoughtful questions at the end to show your interest in the role.',
    '[{"word": "resume", "meaning": "document listing work history"}, {"word": "strength", "meaning": "positive quality"}, {"word": "weakness", "meaning": "area for improvement"}]'::jsonb,
    '[{"rule": "Modals of Advice", "example": "You should dress professionally."}, {"rule": "Imperatives", "example": "Practice common questions."}]'::jsonb,
    2
),
(
    'Climate Change', 
    'Environment', 
    'advanced', 
    'https://www.youtube.com/watch?v=G4H1N_yXBiA', 
    'https://example.com/audio/climate_change.mp3',
    'Climate change refers to long-term shifts in temperatures and weather patterns. While these shifts may be natural, human activities have been the main driver of climate change since the 1800s, primarily due to burning fossil fuels like coal, oil, and gas. Burning fossil fuels generates greenhouse gas emissions that act like a blanket wrapped around the Earth, trapping the sun''s heat and raising temperatures. The consequences of climate change include intense droughts, water scarcity, severe fires, rising sea levels, flooding, melting polar ice, catastrophic storms, and declining biodiversity.',
    '[{"word": "greenhouse gas", "meaning": "gas that traps heat in atmosphere"}, {"word": "fossil fuel", "meaning": "natural fuel like coal or gas"}, {"word": "biodiversity", "meaning": "variety of life in the world"}]'::jsonb,
    '[{"rule": "Passive Voice", "example": "Greenhouse gas emissions are generated by burning fossil fuels."}, {"rule": "Complex Sentences", "example": "While these shifts may be natural, human activities have been the main driver."}]'::jsonb,
    2
);

\echo '--- Inserting Exams ---'
-- Exam for Beginner Lesson (ID 1)
INSERT INTO exams (lesson_id, title, type, level, question, created_by) VALUES
(1, 'Daily Routine Quiz', 'mixed', 'beginner',
 '[
    {"text": "What time do I wake up?", "type": "multiple_choice", "options": ["6 AM", "7 AM", "8 AM"], "answer": "7 AM", "explanation": "The text says: I wake up at 7 AM."},
    {"text": "I ___ my teeth.", "type": "fill_blank", "answer": "brush", "explanation": "Collocation: brush teeth"},
    {"text": "Arrange: breakfast / eat / I", "type": "order_sentence", "answer": "I eat breakfast", "explanation": "Subject + Verb + Object"}
 ]'::jsonb, 2);

-- Exam for Intermediate Lesson (ID 2)
INSERT INTO exams (lesson_id, title, type, level, question, created_by) VALUES
(2, 'Interview Skills Check', 'mixed', 'intermediate',
 '[
    {"text": "What should you do before the interview?", "type": "multiple_choice", "options": ["Sleep late", "Research the company", "Eat a big meal"], "answer": "Research the company", "explanation": "Preparation is key."},
    {"text": "You should maintain ___ contact.", "type": "fill_blank", "answer": "eye", "explanation": "Body language tip."},
    {"text": "Arrange: questions / ask / thoughtful", "type": "order_sentence", "answer": "ask thoughtful questions", "explanation": "Imperative sentence"}
 ]'::jsonb, 2);

\echo '--- Inserting Exercises ---'
-- Exercises for Beginner Lesson (ID 1)
INSERT INTO exercises (lesson_id, title, type, level, questions, created_by) VALUES
(1, 'Rewrite Sentences', 'rewrite_sentence', 'beginner',
 '[
    {"text": "I go to work by bus. (Rewrite using ''take'')", "type": "rewrite_sentence", "answer": "I take the bus to work.", "explanation": "Synonymous phrasing."}
 ]'::jsonb, 2),
(1, 'Speaking Practice', 'speaking', 'beginner',
 '[
    {"text": "Tell us about your morning routine.", "type": "speaking", "answer": "", "explanation": "Speak for 1 minute."}
 ]'::jsonb, 2);

-- Exercises for Intermediate Lesson (ID 2)
INSERT INTO exercises (lesson_id, title, type, level, questions, created_by) VALUES
(2, 'Essay Writing', 'essay', 'intermediate',
 '[
    {"text": "Write a paragraph about your strengths and weaknesses.", "type": "essay", "answer": "", "explanation": "100-150 words."}
 ]'::jsonb, 2);

-- Exercises for Advanced Lesson (ID 3)
INSERT INTO exercises (lesson_id, title, type, level, questions, created_by) VALUES
(3, 'Environmental Discussion', 'speaking', 'advanced',
 '[
    {"text": "Discuss the impact of climate change on your country.", "type": "speaking", "answer": "", "explanation": "Speak for 2-3 minutes."}
 ]'::jsonb, 2);

\echo '--- Seeding Complete ---'
